spring.application.name=franquicia

# variables de entorno
spring.r2dbc.url=r2dbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:franchise_db}
spring.r2dbc.username=${DB_USER:root}
spring.r2dbc.password=${DB_PASSWORD:}

spring.sql.init.mode=always
logging.level.org.springframework.r2dbc=DEBUG