spring.application.name=franquicia

# Configuración de R2DBC para MySQL

spring.r2dbc.url=r2dbc:mysql://localhost:3306/franchise_db
spring.r2dbc.username=root
spring.r2dbc.password=
spring.sql.init.mode=always
logging.level.org.springframework.r2dbc=DEBUG